### ISSUE TITLE
omg run stuck at "Executing default health check"

### ISSUE THREAD

**Issue by darkLord19** [microservices/omg#241] opened 2019-07-15 14:50 UTC
omg cli version: 0.13.7-alpha.5
Description: Docker container is built and started successfully but then stuck at loading dialog,
"Executing default health check"

**Comment by wilzbach** [comment] 2019-07-16 11:13
@darkLord19 can you please post more about how to reproduce this error? Thanks!

**Comment by darkLord19** [comment] 2019-07-16 11:39
@wilzbach https://github.com/darkLord19/storywriter this is the service I am trying to run. About reproducing, I am not sure as I did nothing out of the ordinary. I have local copy of that repo, I cd-ed into it and ran " omg run story -a template='On a fine &2 he saw &1.' -a words='["a sparrow", "morning"]' ". This is full output I get:
```
ℹ Building Docker image
Step 1/7 : FROM 		golang:1.12-alpine as builder
---> 6b21b4c6e7a3
Step 2/7 : WORKDIR		/go
---> Using cache
---> 35dc6c939aa4
Step 3/7 : ADD			app.go .
---> Using cache
---> baf03b8ecf8f
Step 4/7 : RUN			CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-w -s" -o app
---> Using cache
---> 18f9e2bb3dab
Step 5/7 : FROM 		scratch
--->
Step 6/7 : COPY 		--from=builder /go/app /app
---> Using cache
---> 502028a13736
Step 7/7 : ENTRYPOINT  ["/app"]
---> Using cache
---> 50e058bdc39c
Successfully built 50e058bdc39c
Successfully tagged omg/darklord19/storywriter.git:latest
✔ Built Docker image with name: omg/darklord19/storywriter.git
✔ Started Docker container: 90822c508f60
    Executing default health check
```

I am running Docker version 18.09.7-ce, build 2d0083d657

Let me know if you need some docker specific logs

**Comment by Arinono** [comment] 2019-07-17 09:24
The 'default health check' is not really a health check. It  just tries the action a specific number of times until it succeeds (or fails after the number of repeat). Right now, the number of attempts is fixed at 100. So the time until the action completely fails can be long.

Did you let the process end gracefully (even if it takes a lot of time). This is useful for me to know if there's a real issue here (a bug).

If you want, you can provide a [real health check](https://microservice.guide/schema/health/) to your service. This will increase the speed of your service a lot (and it's also a good practice). In the end, this health property will be mandatory. But for now, we are using this 'default health check' even if it' s not the most efficient way of doing it.

**Comment by darkLord19** [comment] 2019-07-17 12:13
@Arinono I left it running for around 2-2.5 hours but it was still stuck. I will let it run for longer and see it if fails.

**Comment by wilzbach** [comment] 2019-07-17 12:50
@darkLord19 if you based your code on `microservices/go`, then you probably need this PR https://github.com/microservices/go/pull/3

This can't be merged yet, because the CI fails at the moment to an OMG regression which is only in `alpha` (https://github.com/microservices/omg/issues/229)

**Comment by Arinono** [comment] 2019-07-17 16:04
> @Arinono I left it running for around 2-2.5 hours but it was still stuck. I will let it run for longer and see it if fails.

There's no need to let it run longer, there's an issue, I leave the issue open.

You can still use the `health` property though

**Comment by darkLord19** [comment] 2019-07-17 16:25
@wilzbach adding health endpoint in the service solves the issue.

**Closed** 2019-07-19 16:15 UTC
